/**
 * Generates `apps/web/lib/abi.ts` from the compiled Foundry artifacts and the ATS package.
 *
 * The client talks to a diamond, which presents the UNION of its facets' functions at one address —
 * so there is no single artifact whose ABI is the right one to use. This merges the facet interfaces
 * Tenor actually calls into one `tenorAbi`, deduplicated by selector.
 *
 * Errors matter as much as functions here. The client's job (SPEC §9.2.5) is to decode a simulated
 * revert into a sentence, and it can only do that if every custom error from every layer is in an ABI
 * viem can match against: Tenor's own, Lattice's `IHTSAdapter`/`IHSSAdapter` typed errors, and ATS's
 * compliance errors. Those come from three different packages, which is exactly why this is generated
 * rather than hand-written.
 *
 * Usage:  bun run gen:abi
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const ROOT = resolve(import.meta.dir, '..')
const FORGE_OUT = resolve(ROOT, 'contracts/out')
const ATS_ART = resolve(ROOT, 'node_modules/@hashgraph/asset-tokenization-contracts/artifacts')
const TARGET = resolve(ROOT, 'apps/web/lib/abi.ts')

type AbiItem = { type: string; name?: string; inputs?: { type: string }[] }

function readForge(name: string): AbiItem[] {
  const p = `${FORGE_OUT}/${name}.sol/${name}.json`
  if (!existsSync(p)) throw new Error(`missing forge artifact ${p} — run \`forge build\` in contracts/`)
  return JSON.parse(readFileSync(p, 'utf8')).abi as AbiItem[]
}

function readAts(relPath: string): AbiItem[] {
  const p = `${ATS_ART}/${relPath}`
  if (!existsSync(p)) throw new Error(`missing ATS artifact ${p} — run \`bun install\``)
  return JSON.parse(readFileSync(p, 'utf8')).abi as AbiItem[]
}

/** Identity of an ABI entry for dedup: kind + name + argument types. */
function key(i: AbiItem): string {
  return `${i.type}:${i.name ?? ''}(${(i.inputs ?? []).map((x) => x.type).join(',')})`
}

function merge(...groups: AbiItem[][]): AbiItem[] {
  const seen = new Set<string>()
  const out: AbiItem[] = []
  for (const g of groups) {
    for (const item of g) {
      // Constructors and fallbacks are meaningless on a diamond's merged surface.
      if (item.type === 'constructor' || item.type === 'fallback' || item.type === 'receive') continue
      const k = key(item)
      if (seen.has(k)) continue
      seen.add(k)
      out.push(item)
    }
  }
  return out
}

// --- the Tenor diamond: every facet the client calls, plus every error it must decode -------------
const tenor = merge(
  readForge('ITenorMarket'),
  readForge('ITenorCoupon'),
  readForge('IDiamondLoupe'),
  readForge('IHTSAdapter'), // associateToken/transferToken + the HTS* typed errors
  readForge('IHSSAdapter'), // scheduleOf + the HSS* typed errors
  readForge('IAccessControl'), // hasRole, for the issuer view
  readForge('Pausable'), // paused()
  readForge('TenorHTS'), // TenorHTSCallFailed / TenorHTSAmountOverflow
  readForge('TenorHSS'),
  readForge('TenorMarketLib'), // lib-level errors surface through the facet
  readForge('TenorCouponLib'),
)

// --- the ATS security token ----------------------------------------------------------------------
const atsToken = merge(
  readAts('contracts/facets/core/ICore.sol/ICore.json'), // decimals, name, symbol
  readAts('contracts/facets/kyc/IKyc.sol/IKyc.json'), // getKycStatusFor — "Verified by issuer"
  readAts('contracts/facets/holdByPartition/IHoldByPartition.sol/IHoldByPartition.json'),
  readAts('contracts/facets/pause/IPause.sol/IPause.json'), // isPaused — "Trading paused by issuer"
  readAts('contracts/facets/freeze/IFreeze.sol/IFreeze.json'), // "Account frozen" — demo beat 5
  readAts('contracts/facets/controlList/IControlList.sol/IControlList.json'),
  readAts('contracts/facets/layer_1/ERC3643/IERC3643Types.sol/IERC3643Types.json'),
  // ATS raises most compliance refusals from a SHARED error interface rather than the facet that
  // checks them — `AccountIsBlocked` lives here, not in IControlList — so without this the client
  // would show a raw selector for the blocklist case the demo exercises.
  readAts('contracts/infrastructure/errors/ICommonErrors.sol/ICommonErrors.json'),
  readAts('@openzeppelin/contracts/token/ERC20/IERC20.sol/IERC20.json'), // balanceOf/approve/allowance
)

// --- the Hedera Token Service at 0x167 (the wallet associates ITSELF with USDC) -------------------
const hts = readForge('IHederaTokenService')
// --- HIP-719 facade on an HTS token address: `isAssociated()` for the setup card ------------------
const hrc719 = readForge('IHRC719')

const banner = `// GENERATED by scripts/gen-abi.ts — do not edit by hand.
// Regenerate with \`bun run gen:abi\` after changing a contract or bumping ATS.
//
// \`tenorAbi\` is the UNION of the diamond's facet interfaces: a diamond presents all of them at one
// address, so no single artifact describes it. Every custom error from every layer is included, because
// decoding a simulated revert into a sentence (SPEC 9.2.5) only works if viem can match the selector.
`

const body = [
  banner,
  `export const tenorAbi = ${JSON.stringify(tenor, null, 2)} as const\n`,
  `export const atsTokenAbi = ${JSON.stringify(atsToken, null, 2)} as const\n`,
  `export const htsAbi = ${JSON.stringify(hts, null, 2)} as const\n`,
  `export const hrc719Abi = ${JSON.stringify(hrc719, null, 2)} as const\n`,
].join('\n')

mkdirSync(dirname(TARGET), { recursive: true })
writeFileSync(TARGET, body)

const count = (a: AbiItem[], t: string) => a.filter((i) => i.type === t).length
console.log(`wrote apps/web/lib/abi.ts`)
console.log(`  tenorAbi     ${count(tenor, 'function')} fns · ${count(tenor, 'event')} events · ${count(tenor, 'error')} errors`)
console.log(`  atsTokenAbi  ${count(atsToken, 'function')} fns · ${count(atsToken, 'error')} errors`)
console.log(`  htsAbi       ${count(hts, 'function')} fns`)
